version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions-dependencies:
        patterns:
          - "*" # Include all actions

  - package-ecosystem: "pip"
    directory: "/tests/data/requirements.txt"
    schedule:
      interval: "monthly"
    groups:
      pip-dependencies:
        patterns:
          - "*" # Include all dependencies
