- id: clang-format-docker
  name: clang-format
  description: Run `clang-format`
  language: docker_image
  files: \.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cu|c\+\+|cxx|tpp|txx)$
  entry: egecetinn/precommit:latest clang-format -i

- id: cppcheck-docker
  name: cppcheck
  description: Run `cppcheck`
  language: docker_image
  files: \.(c|cc|cpp|cu|c\+\+|cxx|tpp|txx)$
  entry: egecetinn/precommit:latest cppcheck --error-exitcode=1
