[files]
extend-exclude = [
                    "build",
                    "cmake",
                    "dist",
                    "doc",
                    "scripts",
                    "thirdparty",
                    "tests/fuzztest",
                    "tests/gtest",
                    "tests/MemPlumber",
                    "codespell-ignore-list.txt"
                 ]

[default.extend-identifiers]


[default.extend-words]
Ege="Ege"


[type.make]
extend-glob = []
check-file = false
