{
 "title": "Linux Hosts Metrics | Base",
 "description": "Basic overview of linux host metrics, based on node_exporter",
 "tags": [
  "linux",
  "node-exporter",
  "ops"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(node_time_seconds{job=\"$job\"},instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_boot_time_seconds,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Host Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$host\",job=\"$job\"} - node_boot_time_seconds{instance=\"$host\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "description": "Amount of memory",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"$host\",job=\"$job\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$host\",job=\"$job\"}[$__rate_interval])))) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$host\",job=\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=\"$host\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Net IN (24h)",
   "type": "stat",
   "description": "Network traffic in the last day",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{instance=~\"$host\"}[24h]))"
    }
   ]
  },
  {
   "title": "Net OUT (24h)",
   "type": "stat",
   "description": "Network traffic in the last day",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=~\"$host\"}[24h]))"
    }
   ]
  },
  {
   "title": "Disk (Free)",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{fstype!~\"(tmpfs|rootfs).*\",instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Hardware temperature monitor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"$host\",job=\"$job\"}",
     "legendFormat": "{{ chip }} {{ sensor }} temp"
    },
    {
     "expr": "node_hwmon_temp_crit_celsius{instance=\"$host\",job=\"$job\"}",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$host\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Processors",
   "type": "stat",
   "description": "Number of processors",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$host\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$host\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$host\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$host\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$host\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$host\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{instance=\"$host\",job=\"$job\"} )) * 100"
    }
   ]
  },
  {
   "title": "Net IN (1h)",
   "type": "stat",
   "description": "Network traffic in the last hour",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{instance=~\"$host\"}[1h]))"
    }
   ]
  },
  {
   "title": "Net OUT (1h)",
   "type": "stat",
   "description": "Network traffic in the last hour",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=~\"$host\"}[1h]))"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "OOM Killer",
   "type": "stat",
   "description": "OOM killer invocations",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_vmstat_oom_kill{instance=\"$host\",job=\"$job\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "CPU Load | $host",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 10 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (mode) (irate(node_cpu_seconds_total{instance=~\"$host\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"$host\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"$host\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Traffic by Packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{instance=\"$host\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_packets_total{instance=\"$host\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Maximum Time Sync Error",
   "type": "stat",
   "description": "Maximum time sync error in seconds",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds{instance=\"$host\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Disk Activity | $host",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 17 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$host\"}[5m]) > 0",
     "legendFormat": "Read ({{device}})"
    },
    {
     "expr": "- irate(node_disk_written_bytes_total{instance=~\"$host\"}[5m]) < 0",
     "legendFormat": "Write ({{device}})"
    }
   ]
  },
  {
   "title": "Disk IO | $host",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 17 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$host\"}[5m]) > 0",
     "legendFormat": "Read ({{device}})"
    },
    {
     "expr": "- irate(node_disk_write_time_seconds_total{instance=~\"$host\"}[5m]) < 0",
     "legendFormat": "Write ({{device}})"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=\"$host\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=\"$host\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Written bytes"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "gauge",
   "description": "Open file descriptors percentage",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$host\",job=\"$job\"} / process_max_fds{instance=\"$host\",job=\"$job\"}"
    }
   ]
  }
 ]
}