{
 "title": "XXX Test Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Host",
    "query": {
     "query": "label_values(XXX_info,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "stat",
   "description": "Version of XXX",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "XXX_info{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "CPU usage of service",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "description": "Memory usage of service",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_usage{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "stat",
   "description": "Disk read/write of service",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_read{instance=\"$instance\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "disk_write{instance=\"$instance\"}",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "stat",
   "description": "Thread count of the service",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thread_count{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "File Descriptor",
   "type": "stat",
   "description": "File descriptor count of service",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "file_descriptor_count{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "stat",
   "description": "Total page faults occurred in service",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(page_faults{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Page faults"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Uptime of the service",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "current_time{instance=\"$instance\"} - init_time{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "ZeroMQ Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Received",
   "type": "stat",
   "description": "Total received commands",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zeromq_received_commands{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Commands",
   "type": "gauge",
   "description": "ZeroMQ failed command percentage",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zeromq_failed_commands{instance=\"$instance\"}/zeromq_received_commands{instance=\"$instance\"}",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Failed Commands",
   "type": "stat",
   "description": "Failed ZeroMQ commands",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zeromq_failed_commands{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(zeromq_uploaded_bytes{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Upload"
    },
    {
     "expr": "rate(zeromq_downloaded_bytes{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Download"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "timeseries",
   "description": "ZeroMQ processing performance",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(zeromq_processing_time_sum{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Processing"
    },
    {
     "expr": "zeromq_minimum_processing_time{instance=\"$instance\"}",
     "legendFormat": "Minimum"
    },
    {
     "expr": "zeromq_maximum_processing_time{instance=\"$instance\"}",
     "legendFormat": "Maximum"
    },
    {
     "expr": "zeromq_processing_time{instance=\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "99th Quantile"
    },
    {
     "expr": "zeromq_processing_time{instance=\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "50th Quantile"
    }
   ]
  },
  {
   "title": "Received Parts",
   "type": "stat",
   "description": "Total received command parts",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zeromq_total_command_parts{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Command Parts",
   "type": "stat",
   "description": "Failed ZeroMQ command parts",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zeromq_failed_command_parts{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Telnet Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Received",
   "type": "stat",
   "description": "Total received commands",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "telnet_received_commands{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "gauge",
   "description": "Active Telnet connections",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "telnet_active_connections{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accepted Connections",
   "type": "stat",
   "description": "Accepted Telnet connections",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "telnet_received_connections{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(telnet_uploaded_bytes{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Upload"
    },
    {
     "expr": "rate(telnet_downloaded_bytes{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Download"
    }
   ]
  },
  {
   "title": "Avg Processing",
   "type": "stat",
   "description": "Average processing time",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "telnet_processing_time_sum{instance=\"$instance\"}/telnet_processing_time_count{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Session duration",
   "type": "timeseries",
   "description": "Telnet session duration",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(telnet_session_duration_sum{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Failed Commands",
   "type": "stat",
   "description": "Failed Telnet commands",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "telnet_failed_commands{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Refused Connections",
   "type": "stat",
   "description": "Refused Telnet connections",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "telnet_refused_connections{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Session",
   "type": "stat",
   "description": "Average session time",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "telnet_session_duration_sum{instance=\"$instance\"}/telnet_session_duration_count{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}