FROM ubuntu:22.04
MAINTAINER egecetinn <egecetin@hotmail.com.tr>
CMD bash

# Configure timezone to avoid user input during build
ENV TZ=US/Pacific
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get -y update && apt-get -y install \
	cppcheck \
	clang-format \
	clang-tidy \
	cmake \
	curl \
	expect \
	gcc \
	g++ \
	gcovr \
	git \
	libcurl4-openssl-dev \
	python3-dev \
	python3-pip \
	python-is-python3 \
	telnet

RUN python3 -m pip install --upgrade pip
