FROM rockylinux:9.1
MAINTAINER egecetinn <egecetin@hotmail.com.tr>
CMD bash

RUN dnf -y update && dnf -y install \
	cmake \
	expect \
	gcc \
	gcc-c++ \
	git \
	libcurl-devel \
	python3-devel \
	telnet

RUN python3 -m pip install --upgrade pip
